### ISSUE TITLE
Build Error with NetBeans

### ISSUE THREAD

**Issue by anuraganands** [jMetal/jMetal#293] opened 2018-10-22 01:10 UTC
I am using NetBeans 8 to build the project where get the following error:

...
Results :

Failed tests: 
  MOMBI2IT.shouldTheHypervolumeHaveAMininumValue:101 null

Tests run: 48, Failures: 1, Errors: 0, Skipped: 3

...
Reactor Summary:

org.uma.jmetal:jmetal ............................. SUCCESS [47.184s]
org.uma.jmetal:jmetal-core ........................ SUCCESS [1:49.595s]
org.uma.jmetal:jmetal-problem ..................... SUCCESS [41.392s]
org.uma.jmetal:jmetal-algorithm ................... FAILURE [3:25.519s]
org.uma.jmetal:jmetal-exec ........................ SKIPPED

**Comment by matthieu-vergne** [comment] 2018-10-22 21:11
Duplicate of #296?

**Closed** 2022-10-06 07:07 UTC
