### ISSUE TITLE
Termination Condition

### ISSUE THREAD

**Issue by shelvin29** [jMetal/jMetal#162] opened 2016-09-05 10:58 UTC
I am working with NSGA2.  Is there a way to specify termination condition in terms of run-time? There are a number of combinatorial problems which are usually compared in terms of run-time rather than function evaluations. If not what would be the best way to go about implementing this. Thanks!

**Comment by matthieu-vergne** [comment] 2016-09-05 12:11
Well, a time-based stopping condition is tricky. I totally agree that it is useful, but it is hard to make objective comparisons with that.

First, the time spent by an algorithm depends on the system it runs on (an algorithm on a fast machine has an obvious advantage if compared to another on a slow machine) and on the actual state of the machine (a computer never runs one thing at a time, but many background processes, and some might run wild, thus consuming extra resources that the algorithm cannot use).

Second, algorithms on computers are rarely suited for such a kind of stopping condition, because they run by steps and the evaluation of the stopping condition is one of these steps. Because the stopping time is reached somewhere between two stop evaluations, you always have a delay between the expected stop and the actual stop. Which means that you can never guarantee to provide the very same amount of time to each algorithm.

To avoid the second problem, you may need to have a constant evaluation of the stopping condition, like in a separated thread, such that when it is reached the algorithm is forced to stop. A simpler way to do is to approximate the reached value at the stopping time by letting it finish its run as usual, taking the result evaluations just before and just after the stop, and approximating the value at the stop through regression. The first problem, however, cannot be avoided without having a dedicated machine. You have to ensure that it is run on the very same machine with the very same settings and without any internal/external disturbances. This is why a time-based stopping condition is rarely reliable.

Once this is said, and if you still want to use such an evaluation, what you can do is to extend NSGAII in order to override the method `isStoppingConditionReached()`, such that it returns true as soon as a given time has passed. Then I don't know if it would be as simple as that for you, because you may use other classes which require to use the NSGAII class and not a child class. But without your code I can't say more.

**Comment by shelvin29** [comment] 2016-09-05 22:41
Thanks matthieu for your prompt response. Ideally I want to check after each evaluation if the stopping criteria has been reached. Currently we have a fresh copy of jmetal with some classes which we have added for the problem definition. Other than that everything is the same. Currently in the default mode in jmetal the stopping criteria is checked after each generation. What would be best way to check after each evaluation without throwing off(causing errors in) other aspects of the framework.

**Comment by ajnebro** [comment] 2016-09-06 07:39
Hi.
  I have coded a first approximation of a NSGA-II version with a stopping condition based on runtime called [NSGAIIStoppingByTime](https://github.com/jMetal/jMetal/blob/master/jmetal-algorithm/src/main/java/org/uma/jmetal/algorithm/multiobjective/nsgaii/NSGAIIStoppingByTime.java) that can be configured and executed with class [NSGAIIStoppingByTimeRunner](https://github.com/jMetal/jMetal/blob/master/jmetal-exec/src/main/java/org/uma/jmetal/runner/multiobjective/NSGAIIStoppingByTimeRunner.java). It seems to work; please feel free to try it.

 This variant inherits from the `NSGAII` class, which requires as parameters the maximum number of evalutions and an evaluator, so I have had to pass 0 and null respectively in the `super()` method, which is not a very attractive solution. Time to think about NSGA-II ...

**Comment by matthieu-vergne** [comment] 2016-09-06 15:46
O~h, what a dirty code... {^.^}~

Not bad Antonio, but clearly you miss the point of cutting short the computing. Because as shown by the [`run()` method](https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/algorithm/impl/AbstractEvolutionaryAlgorithm.java#L66), there is still the population replacement which is done, although you already want it to stop so it is just computing it for nothing. You should also override this one to add the stopping management there too.

Going further, their is several steps before the evaluation of the population, and if the actual stopping time occurs before the first evaluation... well, you get the point: we are still out of the objective when it comes to a time-based stopping criterion. Because Shelvin might be interested in the number of evaluations, while another might be interested in the number of individual generations, which is part of the reproduction step just before the evaluation.

To make it properly time-based, the algorithm should be designed in such a way that it can be stopped at any time, like a killed process, while all the relevant data, like the value returned by `getResult()`, should remain correct. One may think about interrupting the thread through [`Thread.interrupt()`](http://docs.oracle.com/javase/1.5.0/docs/guide/misc/threadPrimitiveDeprecation.html), but if the algorithm is run sequentially rather than in a dedicated thread you would kill everything.

In order to avoid that, what should be done I think is the following:
- remove `isStoppingConditionReached()`, which implies to have an active check of it which is of course not wanted for an anytime-stop,
- make the `run()` loop infinite (`while(true) {...}`)
- put all the loop into a `Thread` and run it, waiting for it to finish
- add a `stop()` method which do the dirty job: interrupt the thread instance
- provide relevant (/!\self-advertisement/!\\) `Measure` instances to the user, for him to decide when to call `stop()`

This way, the user can register a listener on a `Measure` of its choice to call `stop()`, like an evaluation counter or a generation counter, or just run a thread to call `stop()` after a given time has elapsed. For the latter, if we don't want the user to deal with threads, we can just provide him a facility which call a function after a given time, so we are hiding the thread stuff.

At least, I think that this is way more clean and efficient than checking for the stop criteria continuously, which has an unwanted impact on the complexity of the algorithm itself. In particular, the time-based stop-thread could look like this:
```java
public static void runAt(final Runnable action, final long runTime) {
	new Thread(new Runnable() {
		@Override
		public void run() {
			synchronized (this) {
				try {
					long remaining = 1;
					do {
						wait(Math.round(remaining * 0.9));
						remaining = runTime - System.currentTimeMillis();
					} while (remaining > 0);
				} catch (InterruptedException e) {
				} finally {
					action.run();
				}
			}
		}
	}).run();
}
```
Some explanations:
- `action` is the stop call (a `Runnable` which just call the stop method of the algorithm). I just generalised it to any action, so we can use it anywhere.
- the `synchronized (this)` at the start is necessary for `wait()` to work without generating an exception (we need to lock the object on which we wait).
- it is not a naive `wait(runTime - System.currentTimeMillis())` because `wait()` is not 100% precise. It depends on what happens in other threads. This is why I wait 90% of the remaining time (`remaining * 0.9`), so we can check if it still remains time or if it has been completely consumed already. At the start, it should be fine, but closer we are to the stop time, and more often it will check. In my trials, 1000 runs with a stop time 10ms after the start gives an average of 10.106ms per run. For 100ms, it is 100.074ms in average.
- it uses wait before to compute `remaining`, because it is the remaining time *after* the wait which should be checked. Consequently, we need to initialise `remaining` before the loop to compute the first `wait`.
- `remaining` is initialised to 1 instead of 0 because `wait(0)` is equivalent to `wait()`, which means without a time limit. Notice, consequently, the waiting time is always 1 or higher, because otherwise `remaining` should be of 0, which means that the loop has finished just before. If instead of 90% we have less than 50%, then it could have a waiting time of 0, which is not good. So we can increase the safety margin, but not more than 50%. At 90%, the average number of `wait()` calls is 2.779 for 10ms, 3.827 for 100ms (it follows a logarithmic curve). So you see that you are far less than a continuous checking inside the algorithm, with drastic time saving for long periods.
- there is a try-catch because we use `wait()` which can be interrupted, but it is not prone to be interrupted because we wait on a local object (the internal `Runnable`). Anyway, we run the action (the stop call) in the `finally` block, so it is called even if it is interrupted.

You can try it with that (tweak it to make your own statistics):
```java
public static void main(String[] args) {
	final long start = System.currentTimeMillis();
	System.out.println("Start: " + start);
	long delay = 1000;
	long stop = start + delay;
	Runnable stopAction = new Runnable() {
		@Override
		public void run() {
			// stop() call here
			long stop = System.currentTimeMillis();
			System.out.println("Stop: " + stop);
			System.out.println("Duration: " + (stop - start));
		}
	};
	runAt(stopAction, stop);
}
```
Last but not least, I don't have any clue regarding how a multi-threaded algorithm would react to that. I did not look at them, so I don't know. It might work as well without much efforts or not.

**Comment by ajnebro** [comment] 2016-09-07 05:08
> but clearly you miss the point of cutting short the computing

The solution to this depends on how critical is the termination condition. When running NSGA-II to stop after 4000 ms the reported running time is 4002 ms, which doesn't seem to be a significant overhead. 

Of course I have used a benchmark problem; in the case of a real one, which a costly function evaluations, the delay could be more important. In this case, if the user really need to stop the algorithm in exactly a given time, then some approach as the one you suggest should be necessary, but stoppting threads is a delicate matter that should be carefully managed.

**Comment by matthieu-vergne** [comment] 2016-09-07 06:28
I agree. The main point of my solution is how it fully satisfies the
objective (it stops when you ask it to stop) while preserving the algorithm
itself, rather than having to change it completely to manage a single
feature. I agree that stopping a thread should be made carefully, and I
admit that I am not much familiar with this way to do. But several points
make me think that we are in a situation where it can be done cleanly:
- the thread aspect is fully managed by the algorithm (thread launch as
well as interruption) so it does not depend on the user.
- the thread is in the `run()` method, which is supposed to start with a
full initialization and finish with a proper closing, so if well made it
should not depend on the child classes either, with the catch block aiming
at closing properly the algorithm.
- the main potential issue I see is regarding side effects, like a child
class defining a class member which needs some kind of finalization at the
end of a round or of the algorithm (e.g. an open resource to close). But I
wonder if such a situation cannot be managed simply, like using a try-catch
in the child class for catching the interruption, making the closing in the
finally block to ensure that it is always done, and throwing again the
interruption for the parent class to manage it. If the parent class uses
this thread-based process, asking its abstract methods to throw the
exception is a way to remind the programmer that he has to manage this case.

So I think that it can be made cleanly without much efforts. At least, I
think it is worth to try. Once again I am not this familiar with thread
interruptions, but if we can do it then we have a powerful tool for making
a whole bunch of algorithms ready to stop at any time, which seems to me
quite interesting.

**Comment by ajnebro** [comment] 2016-09-07 11:16
The matter is complicated. One the one hand, if we assume that the current evaluation can be interrumpted, the algorithm must finish and that will consume some time (a few milliseconds, but it will require time). On the other hand, interrumpting an ongoing evaluation is problem dependant; for example, it could be a simulator having many open files and connections to some Web services. In these cases we cannot merely interrupt the current computation.

**Comment by matthieu-vergne** [comment] 2016-09-07 14:19
*Small mistake: in my code above I used `Thread.run()` to launch the thread, but it should have been `Thread.start()`, otherwise the parent thread wait for the child thread to finish. It may have some impact on the code, but the idea remain the same.*

Regarding the complexity of concurrency, if you think about web services, and networks in general, losing connection is a usual thing. It is a matter of technics and habits, not a fundamental problem. In particular, we speak about multi-threading, so if a parent thread A requests the interruption of a child thread B, B may spend some more time for terminating properly, but thread A can go ahead after requesting the interruption. So as long as the interrupted child deals first with the data to return for immediate use, then release a lock for the parent to go ahead, the child can then go ahead with closing properly the resources without having much impact on the parent thread. For example, the parent may call `getResult()` just after requesting the interruption, but the method is blocked by the child until the data is ready, then once the data is ready the lock is released and the parent can resume its execution while the child run in parallel to close its resources cleanly.

So I am pretty sure that with a clean code we can achieve something more efficient and practical than you think. If you don't want to work on that, that is fine, but so far you don't have anything else than putting checks everywhere in the algorithm, which is heavy and ugly. It reminds me this time when we did not have exception management in pure C code, and that you had to poll continuously your state variables to know what has happened... You are cruel to make me remember that. {;_;}

But I agree that it needs a careful thinking and design on something which is not usual in our current situation. So just pass on that if you don't feel confident or if you lack time. The idea is there, which is a good thing already.

**Comment by ajnebro** [comment] 2016-09-07 16:09
I'm working in parallel programing since 1990, so that is a staff I know well :). And I still like it :)

The point is that adding these new features will take time, and currently I'm overloaded so I have to think carefully in what devote my time. Think that unless someone be very interested, it is very possible that nobody use them. I'm the main user of jMetal ;), so if I would need that for my research work then I would start to work on it inmediately, but that's not the case right now.

Anyway, as the issue is open, we can return to it in my free time to consider if is worth adding that support.

**Comment by matthieu-vergne** [comment] 2016-09-07 16:45
Well, at least this issue here should be closed somehow, because it is about a specific need. We can have another one about the general purpose and go back to it when we find time.

**Comment by shelvin29** [comment] 2016-09-18 08:45
Thank you guys for your feedback. We have decided to go with Antonio's solution which matches our needs perfectly.

**Closed** 2022-10-06 07:06 UTC
